"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const auth_route_1 = __importDefault(require("./auth.route"));
const event_route_1 = __importDefault(require("./event.route"));
const job_route_1 = __importDefault(require("./job.route"));
const user_route_1 = __importDefault(require("./user.route"));
const candidate_route_1 = __importDefault(require("./candidate.route"));
const recruiter_route_1 = __importDefault(require("./recruiter.route"));
const skill_route_1 = __importDefault(require("./skill.route"));
const interviewer_route_1 = __importDefault(require("./interviewer.route"));
const admin_route_1 = __importDefault(require("./admin.route"));
const routes = (0, express_1.Router)();
routes.use('/api/v1/auth', auth_route_1.default);
routes.use('/api/v1/events', event_route_1.default);
routes.use('/api/v1/jobs', job_route_1.default);
routes.use('/api/v1/user', user_route_1.default);
routes.use('/api/v1/candidate', candidate_route_1.default);
routes.use('/api/v1/recruiter', recruiter_route_1.default);
routes.use('/api/v1/skills', skill_route_1.default);
routes.use('/api/v1/interviewers', interviewer_route_1.default);
routes.use('/api/v1/admin', admin_route_1.default);
exports.default = routes;
